#!/usr/bin/env bash
set -e

# Import the common variables
export script_path=$( dirname "${BASH_SOURCE[0]}"  )
source $script_path/common

vagrant destroy $force gastropub-single-$provider

if ! vagrant status --machine-readable | grep running >/dev/null; then
    rm -f $rehearsal_config
fi
